services:
  node:
    build:
      context: ../be
      dockerfile: DockerfileBE
    container_name: optix-be
    ports:
      - '3000:3000'
  optix:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
